In [4]:
import numpy as np


In [5]:
#1-D array

arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr=np.array(['ANKIT','WADHWA'])
print(arr)

['ANKIT' 'WADHWA']


In [8]:
#2-D array
arr=np.array([[10,20,30,40,50],[11,21,31,41,51]]),
print(arr)

(array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51]]),)


In [9]:
#3-d array
arr3d=np.array([[[10,20,30,40,50],[11,21,31,41,51]],[[15,25,35,45,55],[16,27,37,47,57]]])
print(arr)

(array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51]]),)


In [10]:
#0-d array
arr=np.array(4)
print(arr)

4


In [11]:
#dimension of the array
arr=np.array([10,20,30,40,50])
print(arr.ndim)

1


# accessing array elements




In [12]:
#1-D array
arr1d=np.array([10,20,30,40,50])
print(arr1d[3])
print(arr1d[-2])

40
40


In [13]:
#2-d Array
arr2d=np.array([[10,20,30],[11,21,31]])
print(arr2d)

[[10 20 30]
 [11 21 31]]


In [14]:
arr2d[1,1]

21

In [15]:
#slicing of 1-d array
arr1d=np.array([10,20,30,40,50])
arr1d[1:4]


array([20, 30, 40])

In [16]:
arr1d[-3:4]

array([30, 40])

In [17]:
arr1d[:4]

array([10, 20, 30, 40])

In [18]:
arr1d[2:]

array([30, 40, 50])

In [19]:
arr1d[0:5:2]

array([10, 30, 50])

In [20]:
#slicing on 2-d array
arr2d=np.array([[10,20,30],[11,21,31],[5,6,7]])
arr2d


array([[10, 20, 30],
       [11, 21, 31],
       [ 5,  6,  7]])

In [21]:
arr2d[0:3,1:3]

array([[20, 30],
       [21, 31],
       [ 6,  7]])

In [22]:
#shape of array
arr1d.shape

(5,)

In [23]:
print(arr2d.shape)

(3, 3)


In [24]:
print(arr3d.shape)

(2, 2, 5)


In [25]:
#array reshaping converting 1-d array into 2-d array
arr=np.array([10,20,30,40,50,60])
print(arr,end='\n\n')
print(arr.reshape([2,3]))

[10 20 30 40 50 60]

[[10 20 30]
 [40 50 60]]


In [26]:
arr=np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160])
print(arr)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]


In [27]:
print(arr.reshape([4,2,2]))

[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]

 [[130 140]
  [150 160]]]


# NUMPY arange(start,stop,size,dtype)

In [28]:
arr=np.arange(5) #first 5 elements
print(arr)

[0 1 2 3 4]


In [29]:
arr=np.arange(5,25) #last element not included
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [30]:
arr=np.arange(10,101,5)
arr

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [31]:
#reshaping of array using arange

arr=np.arange(10,50,5)
print(arr)
arr.reshape([4,2])

[10 15 20 25 30 35 40 45]


array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [32]:
arr2=np.arange(9)
print(arr2)
arr2.reshape([3,3])

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
for i in arr:
    print(i)

10
15
20
25
30
35
40
45


In [34]:
for i in arr2d:
    for j in i:
        print(j)

10
20
30
11
21
31
5
6
7


In [35]:
for i in arr2d:
    print(i)

[10 20 30]
[11 21 31]
[5 6 7]


In [36]:
print(arr3d)

[[[10 20 30 40 50]
  [11 21 31 41 51]]

 [[15 25 35 45 55]
  [16 27 37 47 57]]]


In [37]:
for i in arr3d:
    print(i)

[[10 20 30 40 50]
 [11 21 31 41 51]]
[[15 25 35 45 55]
 [16 27 37 47 57]]


In [38]:
for i in arr3d:
    for j in i:
        print(j)

[10 20 30 40 50]
[11 21 31 41 51]
[15 25 35 45 55]
[16 27 37 47 57]


In [39]:
for i in arr3d:
    for j in i:
        for k in j:
            print(k)
    

10
20
30
40
50
11
21
31
41
51
15
25
35
45
55
16
27
37
47
57


In [40]:
#np.nditer( method)

for i in np.nditer(arr2d):
    print(i)

10
20
30
11
21
31
5
6
7


In [41]:
for i in np.nditer(arr3d):
    print(i)

10
20
30
40
50
11
21
31
41
51
15
25
35
45
55
16
27
37
47
57


In [42]:
#concatenate method
arr1=np.arange(9)
arr2=np.arange(15,30,2)
arrc=np.concatenate([arr1,arr2])
arrc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 15, 17, 19, 21, 23, 25, 27, 29])

In [43]:
arr1=np.arange(9)
arr1=arr1.reshape([3,3])
print(arr1,end='\n\n')
arr2=np.arange(15,32,2)
arr2=arr2.reshape([3,3])
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[15 17 19]
 [21 23 25]
 [27 29 31]]


In [44]:
arrc=np.concatenate((arr1,arr2),axis=0)
arrc

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [15, 17, 19],
       [21, 23, 25],
       [27, 29, 31]])

In [45]:
arrc=np.concatenate((arr1,arr2),axis=1)
arrc

array([[ 0,  1,  2, 15, 17, 19],
       [ 3,  4,  5, 21, 23, 25],
       [ 6,  7,  8, 27, 29, 31]])

In [46]:
#searching
#np.where
arr=np.arange(1,20)
print(arr)
print(np.where(arr==6))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([5], dtype=int64),)


In [47]:
x=np.where(arr%4==0)
print(x)
for i in x:
    print(arr[i])

(array([ 3,  7, 11, 15], dtype=int64),)
[ 4  8 12 16]


In [48]:
#sorting
arr=np.array([12,32,232,43,54,43,65,65,6])
print(np.sort(arr))

[  6  12  32  43  43  54  65  65 232]


# shuffle and permutation

In [49]:
from numpy import random
arr1d

array([10, 20, 30, 40, 50])

In [50]:
b=random.shuffle(arr1d) #original array affected
print(arr1d)


[40 30 20 10 50]


In [51]:
arr1d.sort()
arr1d

array([10, 20, 30, 40, 50])

In [52]:
print(random.permutation(arr1d))
print(arr1d)

[20 50 40 30 10]
[10 20 30 40 50]


In [53]:
#matrix operations
#addition
a=np.array([[10,20],[30,40]])
b=np.array([[7,10],[3,4]])
print(a+b)

[[17 30]
 [33 44]]


In [54]:
#subtraction
print(b-a)

[[ -3 -10]
 [-27 -36]]


In [55]:
#multiplication (a[i]*b[i]) not a matrix product 
print(a*b)

[[ 70 200]
 [ 90 160]]


In [56]:
#division
print(a/b)

[[ 1.42857143  2.        ]
 [10.         10.        ]]


In [57]:
#minimum
np.min(a)


10

In [58]:
np.max(a)

40

In [59]:
#diagonal
print(a)
np.diagonal(a)

[[10 20]
 [30 40]]


array([10, 40])

In [60]:
#tranform
print(a)
print(a.T)

[[10 20]
 [30 40]]
[[10 30]
 [20 40]]


In [61]:
#to print off diagonal
print(a)
c=np.rot90(a)
c

[[10 20]
 [30 40]]


array([[20, 40],
       [10, 30]])

In [62]:
np.diagonal(c)

array([20, 30])

In [63]:
#trace=sum of diagonal elements

a.trace()



50

In [64]:
np.trace(a)

50

In [65]:
#statistics
np.mean(a)

25.0

In [66]:
np.median(b)

5.5

In [67]:
np.var(a)

125.0

In [68]:
np.std(a)

11.180339887498949

In [69]:
print(a,'\n\n',b,'\n')
print(np.add(a,b),'\n')
print(np.subtract(a,b),'\n')
print(np.multiply(a,b),'\n')
print(np.divide(a,b))

[[10 20]
 [30 40]] 

 [[ 7 10]
 [ 3  4]] 

[[17 30]
 [33 44]] 

[[ 3 10]
 [27 36]] 

[[ 70 200]
 [ 90 160]] 

[[ 1.42857143  2.        ]
 [10.         10.        ]]


In [70]:
np.dot(a,b)

array([[130, 180],
       [330, 460]])

In [71]:
np.sqrt(a)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [72]:
arr=np.arange(-4,9)
arr

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [73]:
newarr=np.absolute(arr)
newarr

array([4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
arr=np.trunc([-3.166,3.777])
arr

array([-3.,  3.])

In [75]:
np.around(3.1666,2) #round of upto 2 digits

3.17

In [76]:
np.floor([-3.166,3.777]) #small integer value


array([-4.,  3.])

In [77]:
np.ceil([-3.166,3.777]) #higher value 

array([-3.,  4.])

In [78]:
#sumiation
a=np.array([1,2,3])
np.sum(a)

6

In [79]:
b=np.array([3,4,5])
np.sum([a,b])

18

In [80]:
#product or prod
np.product(a)

6

In [81]:
np.product([a,b])

360

In [83]:
np.prod([a,b])

360

In [85]:
#unique elements array
arr=np.array([12,12,34,2,42,5,3,2,2,24,3,42,4,1,13,4,1,3,1,31,12,4,4,22,44,2])
x=np.unique(arr)
x


array([ 1,  2,  3,  4,  5, 12, 13, 22, 24, 31, 34, 42, 44])

In [87]:
a1=np.array([1,2,3,4])
a2=np.array([3,4,5,6])
c=np.union1d(a1,a2)
c

array([1, 2, 3, 4, 5, 6])

In [91]:
d=np.intersect1d(a1,a2)
d

array([3, 4])

# additional array

In [92]:
#creating an empty matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
#creating a matrix with a constant value
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [102]:
#creating an identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [106]:
#creating matrix having random value between 0 and 1
np.random.random((3,3))

array([[0.87003552, 0.16380444, 0.30832789],
       [0.78479615, 0.10729984, 0.55469204],
       [0.19506399, 0.95125055, 0.88882996]])