In [4]:
#import the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#replacing string from numerical column

data=pd.DataFrame({'A':[2,3,4,'5-3',5],'B':[3,5,'-',7,9]})
data

A  B
0    2  3
1    3  5
2    4  -
3  5-3  7
4    5  9

In [6]:
data.replace('-',np.nan)

A    B
0    2  3.0
1    3  5.0
2    4  NaN
3  5-3  7.0
4    5  9.0

In [7]:
#import the dataset
data=pd.read_csv('D:\\Machine learning\\Data.csv')
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [8]:
#check the null values
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

# EXTRACTION OF INDEPENDENT AND DEPENDENT VARIABLES

In [9]:
x=data.iloc[:,:3].values  #independent variables(salary age and country)
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
y=data['Purchased'].values  #dependent variable 
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [11]:
#handle the missing values
from sklearn.impute import SimpleImputer
#first create the object for simpleimputer class
imputer=SimpleImputer()   #object created    #all nan will change to mean is set todefault we can change it by using strateg in() 

#fit the imputer object into the indepen. variable
imputer=imputer.fit(x[:,1:3])   #age and salary


#to replacing the missing data with mean value by transform

x[:,1:3]=imputer.transform(x[:,1:3])
print(x[:,1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


# Encoding The Categorical Data

In [12]:
#categorical data
print(x[:,0])

['France' 'Spain' 'Germany' 'Spain' 'Germany' 'France' 'Spain' 'France'
 'Germany' 'France']


In [13]:
#label encoder   its means that each unique value assigned with a number
from sklearn.preprocessing import LabelEncoder


In [14]:
#create the object
Label_Encoder=LabelEncoder() #object created
x[:,0]=Label_Encoder.fit_transform(x[:,0])   #fit and transforming in one line
print(x[:,0])  

#in label encoding  numerical assigned value compare its like 2>0 but categorical data can't  be compared so we use hot encoding

[0 2 1 2 1 0 2 0 1 0]


In [62]:
#one hot encoder  means make different column for each category
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer([('Country',OneHotEncoder(),[0])],remainder='passthrough')  #object created  '''  [0]==position of country'''

x=ct.fit_transform(x)
print(x)

#first three columns are of france spain and germany    and other columns are visible bcoz of remainder='passthrough'

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [15]:
'''#without remainder = only categorical columns  will be stored in ct1
#one hot encoder  means make different column for each category
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct1=ColumnTransformer([('Country',OneHotEncoder(),[0])])  #object created  '''  [0]==position of country'''

x1=ct1.fit_transform(x)
print(x1)

 '''

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


# avoiding the dummy variable trap

In [63]:
#removing first categorical column bcoz if they both are zero then third will automatically is 1 so dont need all columns

In [64]:

print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [69]:

x=x[:,1:]
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

# split the dataset into train and test

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
train_test_split(x,y,test_size=0.2,random_state=2)  #test_size=0.2 means 20%

# 1st array is x train 
#2nd array is x test
#3rd array is y train
#4th array is y test
#so we store all these data in distinct variables

[array([[0.0, 0.0, 35.0, 58000.0],
        [0.0, 0.0, 44.0, 72000.0],
        [0.0, 0.0, 48.0, 79000.0],
        [1.0, 0.0, 30.0, 54000.0],
        [0.0, 1.0, 38.0, 61000.0],
        [0.0, 1.0, 38.77777777777778, 52000.0],
        [0.0, 0.0, 37.0, 67000.0],
        [1.0, 0.0, 50.0, 83000.0]], dtype=object),
 array([[1.0, 0.0, 40.0, 63777.77777777778],
        [0.0, 1.0, 27.0, 48000.0]], dtype=object),
 array(['Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'No'], dtype=object),
 array(['Yes', 'Yes'], dtype=object)]

In [73]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)  #test_size=0.2 means 20%  #object created
#random_state means its fix this random values of x,y at 2

In [74]:
print(x_train)

[[0.0 0.0 35.0 58000.0]
 [0.0 0.0 44.0 72000.0]
 [0.0 0.0 48.0 79000.0]
 [1.0 0.0 30.0 54000.0]
 [0.0 1.0 38.0 61000.0]
 [0.0 1.0 38.77777777777778 52000.0]
 [0.0 0.0 37.0 67000.0]
 [1.0 0.0 50.0 83000.0]]


In [75]:
print(x_test)

[[1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 27.0 48000.0]]


In [76]:
print(y_train)

['Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No']


In [77]:
print(y_test)

['Yes' 'Yes']


# features scaling

In [79]:
from sklearn.preprocessing import StandardScaler

In [83]:
st=StandardScaler()  #object created
x_train=st.fit_transform(x_train)
#fit store the mean and std value of x 
#transform change value of x
print(x_train)#all values converted between -1 and 1  (x-mean)/std  


x_test=st.transform(x_test)  #same aboe fit will use there so we don't use the fit again other wise std will be different and stored values are far not from  same mean 
print(x_test)


[[-0.57735027 -0.57735027 -0.80667524 -0.72132045]
 [-0.57735027 -0.57735027  0.61764507  0.58171004]
 [-0.57735027 -0.57735027  1.25067632  1.23322529]
 [ 1.73205081 -0.57735027 -1.5979643  -1.09361488]
 [-0.57735027  1.73205081 -0.3319018  -0.44209963]
 [-0.57735027  1.73205081 -0.20881239 -1.27976209]
 [-0.57735027 -0.57735027 -0.49015961  0.11634201]
 [ 1.73205081 -0.57735027  1.56719195  1.60551972]]
[[1.00000000e+00 5.55111512e-17 4.00000000e+01 6.37777778e+04]
 [5.55111512e-17 1.00000000e+00 2.70000000e+01 4.80000000e+04]]
