In [1]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
#for featuring a sentence rows in a column like subjects in email spam detection this will convert sentece into no.'s

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

corpus=['This is the first document',
       'This document is the second document',
       'And this is third one',
       'Is this the first document?',]


In [10]:
vectorizer=CountVectorizer()

In [14]:
x=vectorizer.fit_transform(corpus)
print(x)
print(vectorizer.get_feature_names()) #unique names

  (0, 8)	1
  (0, 3)	1
  (0, 6)	1
  (0, 2)	1
  (0, 1)	1
  (1, 8)	1
  (1, 3)	1
  (1, 6)	1
  (1, 1)	2
  (1, 5)	1
  (2, 8)	1
  (2, 3)	1
  (2, 0)	1
  (2, 7)	1
  (2, 4)	1
  (3, 8)	1
  (3, 3)	1
  (3, 6)	1
  (3, 2)	1
  (3, 1)	1
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']


In [18]:
 print(x.toarray())
corpus=['This is the first document',
       'This document is the second document',
       'And this is third one',
       'Is this the first document?',]
#['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this'] 
# below array tells which word is present in sentence how many times and is 0 ,document is 1..... 

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 0 1 1]
 [0 1 1 1 0 0 1 0 1]]


### analyzer

In [19]:
vectorizer2=CountVectorizer(analyzer='word',ngram_range=(2,2))

In [20]:
x=vectorizer2.fit_transform(corpus)
print(vectorizer2.get_feature_names())

['and this', 'document is', 'first document', 'is the', 'is third', 'is this', 'second document', 'the first', 'the second', 'third one', 'this document', 'this is', 'this the']
