In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
dataset=pd.read_csv('Customer.csv')
dataset

Gender  Age  Salary  Purchased
0     Male   19   19000          0
1     Male   35   20000          0
2   Female   26   43000          0
3   Female   27   57000          0
4     Male   19   76000          0
5     Male   27   58000          0
6   Female   27   84000          0
7   Female   32  150000          1
8     Male   25   33000          0
9   Female   35   65000          0
10  Female   26   80000          0
11  Female   26   52000          0
12    Male   20   86000          0
13    Male   32   18000          0
14    Male   18   82000          0
15    Male   29   80000          0
16    Male   47   25000          1
17    Male   45   26000          1
18    Male   46   28000          1

In [4]:
#extraction of ID and DD
x=dataset.iloc[:,[1,2]].values
y=dataset.iloc[:,3].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000]], dtype=int64)

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
      dtype=int64)

In [6]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
x_train

array([[    47,  25000],
       [    27,  84000],
       [    19,  76000],
       [    26,  43000],
       [    27,  58000],
       [    32,  18000],
       [    35,  65000],
       [    32, 150000],
       [    45,  26000],
       [    26,  52000],
       [    27,  57000],
       [    19,  19000],
       [    29,  80000],
       [    20,  86000]], dtype=int64)

In [7]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [8]:
#logistic regression as it is categorical output(discrete)

from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,y_train)


LogisticRegression()

In [9]:
pred=classifier.predict(x_test)
pred

array([0, 0, 0, 0, 0], dtype=int64)

In [10]:
y_test

array([0, 0, 0, 1, 0], dtype=int64)

In [11]:
from sklearn.metrics import confusion_matrix 
cm=confusion_matrix(y_test,pred)
cm  
#4 means  4 value are predicted correctly and 1 means 1 wrongly
#diagonal values are correct always remember

array([[4, 0],
       [1, 0]], dtype=int64)

In [12]:
p=classifier.predict_proba(x_test)
p

array([[0.77830167, 0.22169833],
       [0.57784895, 0.42215105],
       [0.62668376, 0.37331624],
       [0.6081468 , 0.3918532 ],
       [0.78367143, 0.21632857]])

# Features scaling (used to make each column value equally comparable)            (x-mean)/std

In [13]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()

In [14]:
x_train=sc_x.fit_transform(x_train)  #fit calculate mean and std
x_test=sc_x.transform(x_test)#transforming the x_test values on the basis of x_train fitted value  
x_train

array([[ 2.149452  , -1.02601437],
       [-0.28717375,  0.70708966],
       [-1.26182405,  0.4720925 ],
       [-0.40900504, -0.49727077],
       [-0.28717375, -0.0566511 ],
       [ 0.32198269, -1.23163688],
       [ 0.68747655,  0.14897141],
       [ 0.32198269,  2.6458162 ],
       [ 1.90578942, -0.99663973],
       [-0.40900504, -0.23289897],
       [-0.28717375, -0.08602574],
       [-1.26182405, -1.20226224],
       [-0.04351117,  0.58959108],
       [-1.13999276,  0.76583895]])

In [28]:
#again do logistic now
from sklearn.linear_model import LogisticRegression
classifier1=LogisticRegression()
classifier1.fit(x_train,y_train)


LogisticRegression()

In [29]:
pred1=classifier1.predict(x_test)
pred1

array([0, 0, 0, 1, 0], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix 
cm1=confusion_matrix(y_test,pred1)
cm1  

#now accuracy is 100%

array([[4, 0],
       [0, 1]], dtype=int64)

In [32]:
p1=classifier.predict_proba(x_test)
p1

array([[0.50000231, 0.49999769],
       [0.4999954 , 0.5000046 ],
       [0.4999969 , 0.5000031 ],
       [0.49999632, 0.50000368],
       [0.50000254, 0.49999746]])